# -*- coding: utf-8 -*-
"""CA1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sk21koy0HbgO1dwlDWKe5CRH9ak5hN3D
"""

x=5
print(f"變數x的值是:{x}")
print(f"變數x的記憶體地址是:{id(x)}")